logging:
    level:
        org.springframework: INFO
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
    h2:
        console.enabled: true
        console.path: /h2-console
    jpa:
        show-sql: false
        properties:
            hibernate:
                format-sql: true
