insert into DSL_MODEL values(1,'test1','test');
insert into DSL_MODEL values(2,'홍길동1','test');
insert into DSL_MODEL values(3,'test2','test');
insert into DSL_MODEL values(4,'홍길동2','test');
insert into DSL_MODEL values(5,'test3','test');
insert into DSL_MODEL values(6,'test3','test');
insert into DSL_MODEL values(7,'test4','test');
insert into DSL_MODEL values(8,'test4','test');
insert into DSL_MODEL values(9,'test5','test');
insert into DSL_MODEL values(10,'test5','test');
insert into DSL_MODEL values(11,'test6','test');
insert into DSL_MODEL values(12,'test6','test');
insert into DSL_MODEL values(13,'test7','test');
insert into DSL_MODEL values(14,'test7','test');
insert into DSL_MODEL values(15,'test8','test');
insert into DSL_MODEL values(16,'test8','test');
insert into DSL_MODEL values(17,'test9','test');
insert into DSL_MODEL values(18,'test9','test');
insert into DSL_MODEL values(19,'test10','test');
insert into DSL_MODEL values(20,'test10','test');
insert into DSL_MODEL values(21,'test10','test');
insert into DSL_MODEL values(22,'test10','test');
insert into DSL_MODEL values(23,'test10','test');
insert into DSL_MODEL values(24,'test10','test');
insert into DSL_MODEL values(25,'test10','test');
insert into Basic_Model(name) values('test1');
insert into Basic_Model(name) values('test2');
insert into Basic_Model(name) values('test3');
insert into Basic_Model(name) values('test4');
insert into Basic_Model(name) values('test5');
insert into Basic_Model(name) values('test6');
insert into Basic_Model(name) values('test7');
insert into Basic_Model(name) values('test8');
insert into Basic_Model(name) values('test9');
insert into Basic_Model(name) values('test10');
insert into Board_Model(B_NAME,BASIC_MODEL_ID ) values('board test1',1);
insert into Board_Model(B_NAME,BASIC_MODEL_ID ) values('board test2',2);
insert into Comment_Model(C_Text,BOARD_MODEL_ID ) values('comment test1',1);
insert into Comment_Model(C_Text,BOARD_MODEL_ID ) values('comment test2',1);
insert into Comment_Model(C_Text,BOARD_MODEL_ID ) values('comment test3',2);



